/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fact.h"

int *
fact_1_svc(intpair *argp, struct svc_req *rqstp)
{
	static int  result,n,r;
	//int i;
	
	n=*argp;
	//r=1/n;
	//fact=1;
	printf("Received %d",n);
	//for(i=n;i>0;i--)
	//{
	 //fact=fact*i;		
	//}
	result = 1/n;

	/*
	 * insert server code here
	 */

	return &result;
}
